ERROR - 2016-12-15 10:20:53 - retry - Caught "code: url=http://Personal Censado en Centros de Trabajo message=[Errno -2] Cannot connect to host personal censado en centros de trabajo:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://Personal Censado en Centros de Trabajo, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:20:53 - retry - Caught "code: url=http://Personal Censado en Centros de Trabajo message=[Errno -2] Cannot connect to host personal censado en centros de trabajo:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://Personal Censado en Centros de Trabajo, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:20:54 - retry - Caught "code: url=http://Personal Censado en Centros de Trabajo message=[Errno -2] Cannot connect to host personal censado en centros de trabajo:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://Personal Censado en Centros de Trabajo, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:20:56 - retry - Caught "code: url=http://Personal Censado en Centros de Trabajo message=[Errno -2] Cannot connect to host personal censado en centros de trabajo:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://Personal Censado en Centros de Trabajo, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:20:59 - retry - Caught "code: url=http://Personal Censado en Centros de Trabajo message=[Errno -2] Cannot connect to host personal censado en centros de trabajo:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://Personal Censado en Centros de Trabajo, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:00 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:00 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:11 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:21:11 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:21:20 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:20 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:20 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:21 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:21 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:21:21 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:21:21 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:21:21 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:21:21 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:21:22 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:21:22 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:21:22 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:21:22 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:21:22 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409, remaining tries 3, sleeping 1.60secs
ERROR - 2016-12-15 10:21:23 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:21:23 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:21:23 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:21:24 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:21:27 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:432, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:27 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/kml?f[0]=questionnaire_answer_question:432, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:27 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:411, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:27 - retry - Caught "code: url=http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409 message=[Errno -2] Cannot connect to host www.devtrac.ug:80 ssl:False [Name or service not known] raised=aiohttp.errors.ClientOSError" url:GET method:http://www.devtrac.ug/statistics/analyse/csv?f[0]=questionnaire_answer_question:409, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:33 - retry - Received invalid response code:429 url:http://bit.ly/166AtwD error: response:Too Many Requests
ERROR - 2016-12-15 10:21:33 - retry - Caught "code:429 url=http://bit.ly/166AtwD message=429, message='Too Many Requests' raised=aiohttp.errors.HttpProcessingError" url:GET method:http://bit.ly/166AtwD, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:21:33 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:21:33 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601, remaining tries 2, sleeping 3.20secs
ERROR - 2016-12-15 10:21:46 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601](http://pakresponse.info/LinkClick.aspx?fileticket=mm8MvDjdlrA%3d&tabid=102&mid=601, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:46 - retry - Caught "code: url=http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601 message=Connection timeout to host pakresponse.info:80 ssl:False raised=aiohttp.errors.ClientTimeoutError" url:GET method:http://pakresponse.info/LinkClick.aspx?fileticket=TEPQB9AnFEg%3d&tabid=102&mid=601, remaining tries 1, sleeping 6.40secs
ERROR - 2016-12-15 10:21:49 - retry - Received invalid response code:429 url:http://bit.ly/166AtwD error: response:Too Many Requests
ERROR - 2016-12-15 10:21:49 - retry - Caught "code:429 url=http://bit.ly/166AtwD message=429, message='Too Many Requests' raised=aiohttp.errors.HttpProcessingError" url:GET method:http://bit.ly/166AtwD, remaining tries 4, sleeping 0.80secs
ERROR - 2016-12-15 10:26:23 - retry - Caught "code: url=http://geonode.wfp.org/geoserver/wfs?format_options=charset%3AUTF-8&typename=geonode%3Anga_trs_roads_osm&outputFormat=SHAPE-ZIP&version=1.0.0&service=WFS&request=GetFeature message= raised=concurrent.futures._base.TimeoutError" url:GET method:http://geonode.wfp.org/geoserver/wfs?format_options=charset%3AUTF-8&typename=geonode%3Anga_trs_roads_osm&outputFormat=SHAPE-ZIP&version=1.0.0&service=WFS&request=GetFeature, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:28:32 - retry - Received invalid response code:429 url:http://bit.ly/1yQqLZI error: response:Too Many Requests
ERROR - 2016-12-15 10:28:32 - retry - Caught "code:429 url=http://bit.ly/1yQqLZI message=429, message='Too Many Requests' raised=aiohttp.errors.HttpProcessingError" url:GET method:http://bit.ly/1yQqLZI, remaining tries 5, sleeping 0.40secs
ERROR - 2016-12-15 10:28:49 - retry - Received invalid response code:429 url:http://bit.ly/1yQqLZI error: response:Too Many Requests
ERROR - 2016-12-15 10:28:49 - retry - Caught "code:429 url=http://bit.ly/1yQqLZI message=429, message='Too Many Requests' raised=aiohttp.errors.HttpProcessingError" url:GET method:http://bit.ly/1yQqLZI, remaining tries 4, sleeping 0.80secs
